name: "setup-vcpkg-nuget"
description: "Add vcpkg nuget feed"
inputs:
  package_permission:
    required: true
    description: "Whether to configure publish-capable credentials (true/false)"
  feed_url:
    required: true
    description: "NuGet feed URL"
  nuget_cmd:
    required: true
    description: "Path to nuget.exe"

runs:
  using: "composite"
  steps:
    - name: Add vcpkg nuget feed (consume-only)
      if: ${{ inputs.package_permission == 'false' }}
      shell: bash
      run: |
        ${{ inputs.nuget_cmd }} \
          sources add \
          -Source "https://nuget.pkg.github.com/AUSAXS/index.json" \
          -StorePasswordInClearText \
          -Name GitHubPackages \
          -UserName "${{ github }}" \
          -Password "${{ secrets.GITHUB_TOKEN }}"

    - name: Configure vcpkg nuget credentials (publish only)
      if: ${{ inputs.package_permission == 'true' }}
      shell: bash
      run: |
        ${{ inputs.nuget_cmd }} \
          sources add \
          -Source "https://nuget.pkg.github.com/AUSAXS/index.json" \
          -StorePasswordInClearText \
          -Name GitHubPackages \
          -UserName "${{ github }}" \
          -Password "${{ secrets.GITHUB_TOKEN }}"
        ${{ inputs.nuget_cmd }} \
        setapikey "${{ secrets.GITHUB_TOKEN }}" \
        -Source "https://nuget.pkg.github.com/AUSAXS/index.json"